site_name: شرح تثبيت هاكنتوش بالعربي
repo_url: https://github.com/arhackintosh/artutorial
site_description: اول و اكبر شرح عربي للهاكنتوش
site_author: ARhackintosh
copyright: gplV3
plugins:
  - autolinks
